- repo: honza/vim-snippets

- repo: tpope/vim-repeat

- repo: neoclide/coc.nvim
  merge: 0
  rev: release
  hook_source: source $VIM_PATH/config/plugins/coc.vim

- repo: ybian/smartim
  hook_add: let g:smartim_default = 'com.apple.keylayout.ABC'

- repo: terryma/vim-multiple-cursors


- repo: tpope/vim-surround

- repo: junegunn/vim-easy-align


#disable plugins
- { repo: neovim/nvim-lsp	, if: 0 }

# - { repo: prabirshrestha/asyncomplete.vim	, if: 0 }

- { repo: prabirshrestha/asyncomplete-lsp.vim	, if: 0 }

- { repo: prabirshrestha/vim-lsp	, if: 0 }

- { repo: mattn/vim-lsp-settings	, if: 0 }

- { repo: prabirshrestha/asyncomplete-tags.vim	, if: 0 }

- { repo: wellle/tmux-complete.vim	, if: 0 }

- { repo: prabirshrestha/asyncomplete-ultisnips.vim	, if: 0 }

- { repo: python-mode/python-mode, on_ft: python}


- repo: easymotion/vim-easymotion
  on_map: { n: <Plug> }
  hook_source: |
    let g:EasyMotion_do_mapping = 0
    let g:EasyMotion_prompt = 'Jump to → '
    let g:EasyMotion_keys = 'fjdksweoavn'
    let g:EasyMotion_smartcase = 1
    let g:EasyMotion_use_smartsign_us = 1
